### PR TITLE
Update for node 0.12 + UNIX + CLI client

### PR DESCRIPTION
**Pull request by saper**
- rename Server.js for case-sensitive filesystems
  on UNIX
- Read request completely from the stream
- Somehow support original Gopher cli client (3.0.6)
  
  gopher gopher://host.name:port works
  
  gopher host.name does not work because the client
  assumes we can do Gopher+ and sends us "$" request.

### CODE REVIEW

**Comment by EvanHahn** [comment]
This looks good.

Would you like to take ownership of this project?

**Comment by saper** [comment]
Thanks. I am not really happy about my use of Buffer vs. string here.

Just toying with it :) so probably not a good owner. I wonder if some Gopher+ support shouldn't be added here...

**Comment by EvanHahn** [comment]
Fair enough. Thanks for this patch!

**Comment by saper** [comment]
> Fair enough. Thanks for this patch!

Now thinking about adding basic gopher+ support, since
the CLI gopher client does not connect to this one easily :(

**Pull request merged**
